# Generated by Django 3.1.1 on 2022-11-01 14:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy', ckeditor.fields.RichTextField(blank=True)),
                ('termsandcondition', ckeditor.fields.RichTextField(blank=True)),
                ('dmca', ckeditor.fields.RichTextField(blank=True)),
                ('disclaimer', ckeditor.fields.RichTextField(blank=True)),
                ('contactus', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
