# Generated by Django 3.1.1 on 2022-11-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='pageid',
            field=models.IntegerField(default=101),
        ),
    ]
