# Generated by Django 3.1.1 on 2022-11-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0004_auto_20221101_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloader',
            name='Enable',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=6),
        ),
    ]
