# Generated by Django 3.1.1 on 2022-11-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0005_downloader_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloader',
            name='Body_Title',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='downloader',
            name='Featured_Image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='downloader',
            name='Meta_Description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='downloader',
            name='Meta_Title',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='downloader',
            name='Slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200),
        ),
    ]
