# Generated by Django 3.1.1 on 2022-11-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0006_auto_20221101_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloader',
            name='Logs',
            field=models.ImageField(blank=True, upload_to='uploads/logos/'),
        ),
        migrations.AlterField(
            model_name='downloader',
            name='Featured_Image',
            field=models.ImageField(blank=True, upload_to='uploads/featuredimages/'),
        ),
    ]
