# Generated by Django 3.1.1 on 2022-11-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0007_auto_20221101_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloader',
            old_name='Logs',
            new_name='Logo',
        ),
    ]
