# Generated by Django 3.1.1 on 2022-11-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0008_auto_20221101_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloader',
            name='Recently_Downloaded',
            field=models.TextField(blank=True),
        ),
    ]
