# Generated by Django 3.1.1 on 2022-11-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0009_downloader_recently_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloader',
            name='Updatedon',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
