# Generated by Django 3.1.1 on 2022-11-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0012_headercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='headercode',
            name='pageid',
            field=models.IntegerField(default=101),
        ),
        migrations.AddField(
            model_name='rendertxt',
            name='pageid',
            field=models.IntegerField(default=101),
        ),
    ]
