# Generated by Django 3.1.1 on 2022-11-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0014_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendertxt',
            name='Robots',
            field=models.FileField(blank=True, upload_to='templates/'),
        ),
    ]
