# Generated by Django 3.1.1 on 2022-11-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0015_auto_20221102_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendertxt',
            name='Ads',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rendertxt',
            name='Robots',
            field=models.TextField(blank=True),
        ),
    ]
