# Generated by Django 3.1.1 on 2022-11-02 16:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0016_auto_20221102_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendertxt',
            name='Robots',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
