# Generated by Django 3.1.1 on 2022-11-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0018_auto_20221102_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='pageid',
            field=models.IntegerField(default=101),
        ),
    ]
